[project]
name = "bls-run"
authors = []
description = ""
telemetry = false
requirements = []
[contracts.member-access]
path = "contracts/member-access.clar"
depends_on = []

[contracts.governance-proposals]
path = "contracts/governance-proposals.clar"
depends_on = []

[contracts.fund-manager]
path = "contracts/fund-manager.clar"
depends_on = []

[contracts.vote-mechanism]
path = "contracts/vote-mechanism.clar"
depends_on = []

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
